<?php
/**
 * Created by PhpStorm.
 * User: gor-admin
 * Date: 5/18/21
 * Time: 6:38 PM
 */
?>

<?= $this->getChildHtml('product.info.type'); ?>

<?= $this->getChildHtml('product.info.review'); ?>

<?= $this->getChildHtml('page.main.title'); ?>

<?= $this->getChildHtml('product.info.price'); ?>

<?= $this->getChildHtml('product.info.overview'); ?>

<?= $this->getChildHtml('product.info'); ?>

<?= $this->getChildHtml('product.info.sku'); ?>

<div class="social-links">
    <?= $this->getChildHtml('social_links_4'); ?>
</div>
