<div class="footer-content">
    <div class="footer content">
        <div class="row">
            <div class="footer-text">
                <?= $this->getChildHtml('footer.top.block'); ?>
            </div>
            <div class="footer-signup">
                <?= $this->getChildHtml('subscribe'); ?>
            </div>
        </div>
    </div>
</div>
<div class="footer content">
    <div class="footer-link-icon row">
        <?= $this->getChildHtml('footer.bottom.links') ?>
        <?= $this->getChildHtml('footer.bottom.icons') ?>
    </div>
</div>

