<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="head-title">
    <h1><?= $block->escapeHtml(__('Sign In')) ?></h1>
</div>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field email required">
                    <div class="control">
                        <input name="login[username]" placeholder="<?= $block->escapeHtml(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input name="login[password]" placeholder="<?= $block->escapeHtml(__('Password')) ?>" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="secondary"><a class="action remind" id="forgot-pass" href="#"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="primary"><button type="submit" class="action facebook primary" title="<?= $block->escapeHtmlAttr(__('ՄՈՒՏՔ ԳՈՐԾԵԼ FACEBOOK-Ի ՄԻՋՈՑՈՎ')) ?>"><span><?= $block->escapeHtml(__('ՄՈՒՏՔ ԳՈՐԾԵԼ FACEBOOK-Ի ՄԻՋՈՑՈՎ')) ?></span></button></div>
                    <div class="third-action"><a class="action signup" id="signupaction" href="#"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a></div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
        </form>
    </div>
</div>
