<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Register $block */
?>
<div class="head-title register-modal-head">
    <h1><?= $block->escapeHtml(__('Գրանցում')) ?></h1>
</div>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">

        <div class="field field-name-firstname required">
            <div class="control">
                <input type="text" placeholder="<?= $block->escapeHtml(__('First Name')) ?>" id="firstname" name="firstname" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}">
            </div>
        </div>
        <div class="field field-name-lastname required">
            <div class="control">
                <input type="text" id="lastname" placeholder="<?= $block->escapeHtml(__('Last Name')) ?>" name="lastname" value="" title="Last Name" class="input-text required-entry" data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <div class="control">
                <input type="email" name="email" placeholder="<?= $block->escapeHtml(__('Email')) ?>" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field password required">
            <div class="control">
                <input type="password" name="password" id="password"
                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                       class="input-text"
                       placeholder="<?= $block->escapeHtml(__('Password')) ?>"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></button>
        </div>
        <div class="primary">
            <button type="submit" class="action facebook primary" title="<?= $block->escapeHtmlAttr(__('ԳՐԱՆՑՎԵԼ FACEBOOK-Ի ՄԻՋՈՑՈՎ')) ?>"><span><?= $block->escapeHtml(__('ԳՐԱՆՑՎԵԼ FACEBOOK-Ի ՄԻՋՈՑՈՎ')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
