<?php
/* @var $block \Aheadworks\OneStepCheckout\Block\Checkout */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container <?= !$block->isCustomerLoggedIn() ? 'aw-osc_customer-not-logged-in' : '' ?>">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @noEscape */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @noEscape */ \Zend_Json::encode($block->getCheckoutConfig()) ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @noEscape */ $block->getBaseUrl() ?>');
        })
    </script>
</div>
<script type="text/javascript">
    require([
        "jquery"
    ], function ($) {
        $(document).on('click', '#edit-form-payment', function () {
            $(".payment-methods > .group-content").addClass('edit-payment');
            $(".payment-methods > .group-content").removeClass('not-edit-payment');
            $("#edit-form-payment").css('display', 'none');
            $("#edit-form-payment-btn").css('display', 'block');
        });

        $(document).on('click', '#edit-form-payment-btn button', function () {
            $(".payment-methods > .group-content").removeClass('edit-payment');
            $(".payment-methods > .group-content").addClass('not-edit-payment');
            $("#edit-form-payment").css('display', 'unset');
            $("#edit-form-payment-btn").css('display', 'none');
        });


        $(document).on('click', '#edit-form-shipping', function () {
            $(".shipping-address").addClass('edit-shipping');
            $(".shipping-address").removeClass('not-edit-shipping');
            $(".shipping-method").addClass('edit-shipping');
            $(".shipping-method").removeClass('not-edit-shipping');
            $("#edit-form-shipping").css('display', 'none');
            $("#edit-form-shipping-btn").css('display', 'block');
        });

        $(document).on('click', '#edit-form-shipping-btn button', function () {
            $(".shipping-address").removeClass('edit-shipping');
            $(".shipping-address").addClass('not-edit-shipping');
            $(".shipping-method").removeClass('edit-shipping');
            $(".shipping-method").addClass('not-edit-shipping');
            $("#edit-form-shipping").css('display', 'unset');
            $("#edit-form-shipping-btn").css('display', 'none');
        });

    });
</script>
