<?php
?>
<div class="row">
    <div class="column">
        <?= $this->getChildHtml('column_1') ?>
    </div>
    <div class="column">
        <?= $this->getChildHtml('column_2') ?>
    </div>
    <div class="column">
        <?= $this->getChildHtml('column_3') ?>
    </div>
    <div class="column">
        <?= $this->getChildHtml('column_4_top'); ?>
        <!--sign up block move-->
        <?= $this->getChildHtml('subscribe'); ?>
        <div class="icons-part">
            <?= $this->getChildHtml('column_4_bottom'); ?>
        </div>
    </div>
</div>
